export const GET_WEATHER_DETAIL = 'detail/GET_WEATHER_DETAIL_REQUEST';
export const GET_WEATHER_DETAIL_LOADING = 'detail/GET_WEATHER_DETAIL_LOADING';
export const GET_WEATHER_DETAIL_SUCCESS = 'detail/GET_WEATHER_DETAIL_SUCCESS';
export const GET_WEATHER_DETAIL_FAILURE = 'detail/GET_WEATHER_DETAIL_FAILURE';
